# Generated by Django 5.1.1 on 2024-11-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_rename_phone_number_appuser_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='WebUser',
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
