# Generated by Django 5.1.1 on 2024-11-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_rename_appuser_webuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebUser',
            new_name='User',
        ),
    ]
